### ISSUE TITLE
Getting everytime "Cannot batch tensors with different shapes in component 0. First element had shape [...]"

### ISSUE THREAD

**Issue by Bienoise** [rncm-prism/prism-samplernn#13]
Hi again, 
I set up everything again by creating a fresh Colab, and it was working. I got 1400 4 seconds audio chunks I'm working on.

After some steps of the training, during the corpus loading, I get a variation on this error:

File "train.py", line 332, in <module>
    main()
  File "train.py", line 323, in main
    verbose=0,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 862, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [132300,1] and element 183 had shape [83571,1].
  
  
  The samples are all the same length.

My parameters:
!python train.py \
  --data_dir /content/drive/MyDrive/prism-samplernn/chunks \
  --num_epochs 100 \
  --batch_size 200 \
  --max_checkpoints 5 \
  --checkpoint_every 1 \
  --output_file_dur 5 \
  --sample_rate 11025 \
  --learning_rate 0.01 \
  --resume True \
  --config_file /content/drive/MyDrive/prism-samplernn/bns.config.json

{
   "seq_len": 1024,
    "frame_sizes": [16,64],
    "dim": 1024,
    "rnn_type": "lstm",
    "num_rnn_layers": 4,
    "q_type": "linear",
    "q_levels": 256,
    "emb_size": 256,
    "skip_conn": true
}

But even with different parameters (lower learning rate, 16 \ 64 \ 128 batch size) I get the error.
I really hope there's an obvious solution to this!  

Thanks a lot.

**Comment by relativeflux** [comment]
@Bienoise Thanks for notifying, I'll look into this. It does seem to be something relating to the data pipeline, at least the part that actually builds the dataset. Which would seem to correspond with the point you're seeing the error, certainly. I'll run it with a dataset of the same size on Colab and my local machine.

Does this seem to happen arbitrarily, or can you not get past the first epoch? Or does it happen inside an epoch, when loading the corpus?

**Comment by Bienoise** [comment]
Thanks to you for the help!

It happens during the loading of any chunk of the corpus, inside an epoch. I definitely got past the first epoch at least once.
The files are mono .wav 22050hz.
If you need me to run experiments with different dataset size just ask!

This is the full error:

Traceback (most recent call last):
  File "train.py", line 332, in <module>
    main()
  File "train.py", line 323, in main
    verbose=0,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 862, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [132300,1] and element 183 had shape [83571,1].
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 2113, in execution_mode
    yield

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 733, in _next_internal
    output_shapes=self._flat_output_shapes)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2579, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [132300,1] and element 183 had shape [83571,1]. [Op:IteratorGetNext]


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/content/drive/My Drive/prism-samplernn/dataset.py", line 31, in get_subseq
    for batch in dataset:

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 747, in __next__
    return self._next_internal()

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 739, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)

  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 2116, in execution_mode
    executor_new.wait()

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py", line 69, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)

tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [132300,1] and element 183 had shape [83571,1].


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
	 [[Equal_1/_34]]
  (1) Unknown:  InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [132300,1] and element 183 had shape [83571,1].
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 2113, in execution_mode
    yield

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 733, in _next_internal
    output_shapes=self._flat_output_shapes)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2579, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [132300,1] and element 183 had shape [83571,1]. [Op:IteratorGetNext]


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/content/drive/My Drive/prism-samplernn/dataset.py", line 31, in get_subseq
    for batch in dataset:

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 747, in __next__
    return self._next_internal()

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 739, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)

  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 2116, in execution_mode
    executor_new.wait()

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py", line 69, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)

tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [132300,1] and element 183 had shape [83571,1].


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_16322]

Function call stack:
train_function -> train_function

**Comment by relativeflux** [comment]
@Bienoise Thanks, that's very helpful. From that trace I can see that it's clearly having problems with batching during the dataset creation. And the fact that it's happening at arbitrary points suggests to me that there might well be a chunk that's not the same size as the others. I just tested on Colab with a dataset with a chunk half the size of the others and I get exactly that error... So maybe it's that? Perhaps the chunking script has a bug, or a chunk of different size somehow found its way in to the dataset?

**Comment by Bienoise** [comment]
I didn't use the chinking script for this one, I used Audacity to create the chunks. They are all the same size (259 kb, 5 secs) and I checked them personally because I feared this was the reason (in fact I found a much longer one which was causing the same problem).
But if you confirm that that's the problem, I'll split the audio using your script: what I'm thinking is that Audacity is not sample-level precise in this task, for some reason.

Will get back after trying, thank you!

**Comment by relativeflux** [comment]
Thanks! Indeed let me know how you get on.

**Comment by Bienoise** [comment]
Hi! After using your script for splitting, the model trained for the entire night without issues - obviously it was my fault! Today I learned that Audacity is not precise in slicing audio files.

Right now accuracy is oscillating but staying quite low, I'll let it train for some epochs or change the dataset (I chose a quite erratic band: https://youtu.be/viHayo0rs9o).

Thank you again.

**Comment by relativeflux** [comment]
Thanks! Glad the script worked OK.

I never got good results with 4 second chunks, though. My best resuts usually come with 8 second chunks with an overlap of 5 - 7 seconds. And with LSTM and skip connections.

Thanks for introducing me to that band! Never trained on anything like that.
