### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by AshleighHazel** [rncm-prism/prism-samplernn#19]
Hello,
Sorry if this is a naive question very new to python. I'm running the code in a colab note book and I keep getting this error for the train.py script

Traceback (most recent call last):
  File "train.py", line 335, in <module>
    main()
  File "train.py", line 257, in main
    samples0, _ = librosa.load(train_split[0], sr=None, mono=True)
IndexError: list index out of range

I'm using all default parameters. 

Thanks
Ash

**Comment by relativeflux** [comment]
@AshleighHazel Hi there, thanks for getting in touch. This looks like a problem with your dataset, either its contents or the location you're passing.

Your dataset should be a folder of audio chunks, prepared using the chunk_audio.py script (technically you don't need to use that script, as long as you have a folder of audio chunks of equal length that willbe fine). Typically I work with 8 second chunks.

Or perhaps the issue is the location of the dataset. Are you sure you're passing the right path, via the `--data_dir` param to train.py?

**Comment by AshleighHazel** [comment]
@relativeflux Thanks so much for your response, it seems like my data set was just too small for the parameters I was using, I uploaded a longer audio file and it is working now. Thanks for pointing me in the right direction and for the code, loving the results!
