### ISSUE TITLE
Inference File Name Issues

### ISSUE THREAD

**Issue by deccolquitt** [rncm-prism/prism-samplernn#23]
When trying to generate audio from a trained model, I am met with the following error: 

2021-09-05 13:52:58.724637: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /content/drive/MyDrive/prism-samplernn/logdir/default/11.08.2021_18.02.32/model.ckpt-46.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "generate.py", line 150, in <module>
    main()
  File "generate.py", line 146, in main
    args.sample_rate, args.temperature, args.seed, args.seed_offset)
  File "generate.py", line 98, in generate
    model = create_inference_model(ckpt_path, num_seqs, config)
  File "generate.py", line 74, in create_inference_model
    model.load_weights(ckpt_path).expect_partial()
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 2354, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

I have had this issue previously and it was solved by changing 'model.ckpt-46.data-00000-of-00001' to 'model.ckpt-46'.

also see: [https://github.com/tensorflow/models/issues/2675](url)

However, once I have done this I am now met with the following error: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 71, in get_tensor
    self, compat.as_bytes(tensor_str))
RuntimeError: /content/drive/MyDrive/prism-samplernn/logdir/default/11.08.2021_18.02.32/model.ckpt-46.data-00000-of-00001; No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate.py", line 150, in <module>
    main()
  File "generate.py", line 146, in main
    args.sample_rate, args.temperature, args.seed, args.seed_offset)
  File "generate.py", line 98, in generate
    model = create_inference_model(ckpt_path, num_seqs, config)
  File "generate.py", line 74, in create_inference_model
    model.load_weights(ckpt_path).expect_partial()
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 2331, in load_weights
    status = self._trackable_saver.restore(filepath, options)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/tracking/util.py", line 1345, in restore
    object_graph_string = reader.get_tensor(base.OBJECT_GRAPH_PROTO_KEY)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 75, in get_tensor
    error_translator(e)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 49, in error_translator
    raise errors_impl.OpError(None, None, error_message, errors_impl.UNKNOWN)
tensorflow.python.framework.errors_impl.OpError: /content/drive/MyDrive/prism-samplernn/logdir/default/11.08.2021_18.02.32/model.ckpt-46.data-00000-of-00001; No such file or directory

Is this a problem with py_checkpoint_reader.py still looking for the 'data-00000-of-00001' suffix? I am not sure how to access it to rectify this. Thanks in advance.

**Comment by relativeflux** [comment]
@deccolquitt What is the full script call you are using, with parameters?

TF will internally still look for the files with the extension `.data-00000-of-00001`, so I don't think that's the issue.

This is on Colab, I assume? The full path looks suspicious:

`/content/drive/MyDrive/prism-samplernn/logdir/default/11.08.2021_18.02.32/model.ckpt-46.data-00000-of-00001`

I'm thinking of the `/content/drive/MyDrive/` bit, I'd expect that to be `/content/drive/My\ Drive/` or `'/content/drive/My Drive/'`. But perhaps that is just TF's internal representation.

**Comment by deccolquitt** [comment]
It is on Colab yes, and I've not previously had a problem with `/MyDrive/` over `/My\ Drive/` or `/My Drive/`, but I have just tried all three as well as finally trying the following which mirrors the output path:

```
!python generate.py \
  --output_path ./generated/default/test.wav \
  --checkpoint_path ./logdir/default/11.08.2021_18.02.32/model.ckpt-46 \
  --dur 10 \
  --sample_rate 16000 \
  --temperature 0.9 \
  --config_file ./default.config.json
```

but I've still gotten the same message as before (I am including the full output this time):

```
2021-09-05 18:02:46.464058: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-05 18:02:46.471822: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-05 18:02:46.472459: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-05 18:02:46.473489: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-05 18:02:46.474172: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-05 18:02:46.474826: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-05 18:02:47.086917: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-05 18:02:47.087662: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-05 18:02:47.088325: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-05 18:02:47.088878: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2021-09-05 18:02:47.088930: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13839 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
2021-09-05 18:02:48.726549: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8004
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 71, in get_tensor
    self, compat.as_bytes(tensor_str))
RuntimeError: ./logdir/default/11.08.2021_18.02.32/model.ckpt-46.data-00000-of-00001; No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate.py", line 150, in <module>
    main()
  File "generate.py", line 146, in main
    args.sample_rate, args.temperature, args.seed, args.seed_offset)
  File "generate.py", line 98, in generate
    model = create_inference_model(ckpt_path, num_seqs, config)
  File "generate.py", line 74, in create_inference_model
    model.load_weights(ckpt_path).expect_partial()
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 2331, in load_weights
    status = self._trackable_saver.restore(filepath, options)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/tracking/util.py", line 1345, in restore
    object_graph_string = reader.get_tensor(base.OBJECT_GRAPH_PROTO_KEY)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 75, in get_tensor
    error_translator(e)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 49, in error_translator
    raise errors_impl.OpError(None, None, error_message, errors_impl.UNKNOWN)
tensorflow.python.framework.errors_impl.OpError: ./logdir/default/11.08.2021_18.02.32/model.ckpt-46.data-00000-of-00001; No such file or directory
```

**Comment by relativeflux** [comment]
And you're sure `./logdir/default/11.08.2021_18.02.32` exists? And there are checkpoint files inside it?

**Comment by deccolquitt** [comment]
100%! 

<img width="504" alt="Screenshot 2021-09-05 at 19 29 35" src="https://user-images.githubusercontent.com/69871889/132137554-ab0c7b0e-1e71-4f90-8a93-e84d69f67378.png">

<img width="552" alt="Screenshot 2021-09-05 at 19 29 42" src="https://user-images.githubusercontent.com/69871889/132137558-2021fd99-d170-4434-8916-a04d4827b016.png">

**Comment by relativeflux** [comment]
OK, so you're definitely missing the data file, then. This is what I typically see (just did a quick Colab test):

<img width="1097" alt="Screenshot 2021-09-05 at 19 34 25" src="https://user-images.githubusercontent.com/17030640/132137675-7166dcdb-0408-4ea5-beb0-4dd681bdd9b2.png">

So your model.ckpt-46 file is somehow missing the `data-00000-of-00001` extension/suffix. I'd suggest doing a quick training test of 1 epoch maybe, just to see if it's saving checkpoints correctly. And if it is I guess you could add the suffix manually, if the file itself is OK that shouldn't be a peoblem.

**Comment by deccolquitt** [comment]
Ah no, this is the original problem - the checkpoints do always save with the `data-00000-of-00001` suffix for me as well, but this has in the past (and also in this case) been a problem with inference, as outlined here: 

[https://github.com/tensorflow/models/issues/2675]

So I have manually removed the suffix, which in the past solved the problem, but in this case didn't. When I try and run with the suffix in place, I am met with this error:

`Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?`

Which is why I manually removed the suffix.

**Comment by relativeflux** [comment]
Thanks for that update. So I've been doing some tests on Colab today, and also on my own machine, and I haven't been able to reproduce the error - certainly not the original error, at any rate. If I remove the extension from the checkpoint file then certainly I get the file not found error. But looking closer at the original error I can see that it references h5py, which is the package required to save entire TF/Keras models (the complete layer architecture) - prism-samplernn internally uses Keras ModelCheckpoint callbacks, which save just the network _weights_, not the model itslef. Googling this error

`Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?`

yields a bunch of results relating to that file format.

I wonder whether the model was saved by an earlier version of TensorFlow, and is now being loaded in the latest one? Perhaps some change has been made which causes models saved by earlier TF versions to not be loadable (although I wouldn't expect that)... On Colab I see they are using 2.6.0 - I believe this is quite a recent upgrade.

I would suggest running a quick test of maybe a single epoch to see if the resulting checkpoints will load during generation.

**Comment by deccolquitt** [comment]
apologies for delay in replying... i have managed to get this to work finally, which i achieved by cloning the repo into the colab session storage, rather than working from a notebook in my drive (although this hasn't been a problem in the past). All I did then (and will do in the future for inference) is dragged my pkl file into the session storage from my drive. thanks for your help.
