### ISSUE TITLE
New errors

### ISSUE THREAD

**Issue by mttjcksn** [rncm-prism/prism-samplernn#8]
Morning,

I just pulled the latest and tried to use skip_conn in my config file as follows:

![image](https://user-images.githubusercontent.com/47283046/101151868-36b7d900-361a-11eb-99e2-129c67c57c31.png)

and running the train.py script like this:

` !python train.py \
  --id 0 \
  --data_dir ./chunks \
  --num_epochs 4 \
  --batch_size 106 \
  --max_checkpoints 4 \
  --checkpoint_every 1 \
  --generate false \
  --sample_rate 22050 \
  --learning_rate 0.001 \
  --reduce_learning_rate_after 1 `

But when running, after loading the first batch of audio files, I get one of the the two following errors:

`Traceback (most recent call last):
  File "train.py", line 332, in <module>
    main()
  File "train.py", line 323, in main
    verbose=0,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.CancelledError:  [_Derived_]RecvAsync is cancelled.
	 [[{{node Equal_1/_66}}]]
	 [[StatefulPartitionedCall/Adam/Adam/update_40/truediv/_56]] [Op:__inference_train_function_16653]

Function call stack:
train_function`

`Traceback (most recent call last):
  File "train.py", line 332, in <module>
    main()
  File "train.py", line 313, in main
    model(init_data)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/content/drive/My Drive/prism-samplernn/samplernn/model.py", line 125, in call
    tf.cast(inputs, tf.float32)[:, : -self.big_frame_size, :]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/content/drive/My Drive/prism-samplernn/samplernn/frame_rnn.py", line 47, in call
    frame_outputs = self.rnn(input_frames)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/content/drive/My Drive/prism-samplernn/samplernn/nn.py", line 85, in call
    out += self.run_dense(name, seqs)
  File "/content/drive/My Drive/prism-samplernn/samplernn/nn.py", line 72, in run_dense
    dense = self.__getattribute__(name + '_skip_out')
AttributeError: 'RNN' object has no attribute 'layer_0_skip_out'`

I've tried running it a few times, sometimes I get the first error, sometimes the second. 

After pulling the latest I made sure to install keras-tuner, even though I'm not using the tine script. I couldn't see anything else new that I'm missing.

Many thanks

**Comment by relativeflux** [comment]
@mttjcksn Hi, I couldn't reproduce the error using the configuration and params you posted, although from the error message I can see it's related to the skip connections layer. You have a repeated key i `q_type` in you JSON config file, but I tested with that and it did work... I assume this is on the Colab notebook? That has been updated recently too, although even the older version should still work with the newest code.... I'd suggest creating a new notebook from the current one (same address), and then clone the repo again. Apologies.

I notice you have a batch size of 106... I didn't try that, but I have had issuues (albeit only on WIndows) LSTM with batch sizes that weren't clean multiples of 8. That seems to be a TensorFlow bug.

**Comment by relativeflux** [comment]
@mttjcksn Hmmm, if you're running this on Colab it might be an allocation issue. I just ran it on a large dataset with your 106 batch size, and it gave me an OOM error, but I also commented out the lines in train.py which suppress the annoying TensorFlow initialization messages... which also seems to suppress some error messages on Colab. Try commenting out the relevant lines in train.py as follows:

```
#os.environ["KMP_AFFINITY"] = "noverbose"
#os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf
#tf.get_logger().setLevel('ERROR')
#tf.autograph.set_verbosity(3)
```

**Comment by mttjcksn** [comment]
Well, whatever it was, I made a new notebook, cloned the repo, set batch_size to 64,  and now it's working 👍 

Thanks for your help
